export const researchFindings = [
  "Cardiology: SGLT2 Inhibitors Slash Heart Failure Risk by 35% in Type 2 Diabetes Patients",
  "Psychiatry: Low-Dose Ketamine Shows 70% Response Rate in Treatment-Resistant Depression",
  "Pediatrics: New RSV Vaccine Reduces Infant Hospitalizations by 82% in Phase 3 Trials",
  "Surgery: Robotic-Assisted Hysterectomy Cuts Hospital Stay by 1.5 Days, Study Finds",
  "Infectious Diseases: Uganda’s Malaria Vaccine Program Reduces Child Mortality by 25%",
  "Oncology: AI-Driven Mammography Boosts Breast Cancer Detection Rates by 15%",
  "Endocrinology: Continuous Glucose Monitoring Lowers HbA1c by 1.2% in Type 1 Diabetes",
  "Neurology: Lecanemab Slows Alzheimer’s Progression by 27% in Early-Stage Patients",
  "Oncology: Mobile Clinics Increase Cervical Cancer Screening by 40% in Rural Kenya",
  "Dermatology: FDA Approves Upadacitinib for Moderate-to-Severe Atopic Dermatitis",
  "Gastroenterology: Fecal Microbiota Transplants Reduce IBS Symptoms in 60% of Patients",
  "Pulmonology: Triple Inhaler Therapy Cuts COPD Exacerbations by 30%, Trial Shows",
  "Infectious Diseases: mRNA-Based Dengue Vaccine Achieves 80% Efficacy in Phase 2 Study",
  "Cardiology: Wearable ECG Devices Predict Atrial Fibrillation with 95% Accuracy",
  "Oncology: CAR-T Cell Therapy Extends Remission in 70% of Leukemia Patients",
  "Neurology: Non-Invasive Brain Stimulation Improves Parkinson’s Motor Symptoms by 25%",
  "Endocrinology: Semaglutide Reduces Cardiovascular Events by 20% in Obese Patients",
  "Pediatrics: Gene Therapy Restores Hearing in 80% of Children with Congenital Deafness",
  "Psychiatry: Psilocybin Therapy Shows 65% Remission Rate for Severe Depression",
  "Infectious Diseases: New Antiviral Cuts COVID-19 Hospitalizations by 50% in High-Risk Groups",
  "Oncology: Liquid Biopsies Detect Lung Cancer Recurrence 6 Months Earlier Than CT Scans",
  "Cardiology: PCSK9 Inhibitors Lower LDL Cholesterol by 60% in Statin-Intolerant Patients",
  "Neurology: Blood-Based Biomarker Test Predicts Alzheimer’s Risk with 90% Accuracy",
  "Dermatology: Biologic Dupilumab Reduces Eczema Flares by 55% in Children",
  "Gastroenterology: GLP-1 Agonists Improve Liver Fibrosis in 40% of NAFLD Patients",
  "Infectious Diseases: Single-Dose HPV Vaccine Shows 90% Efficacy in Preventing Cervical Cancer",
  "Pediatrics: Probiotics Reduce Colic Symptoms in 70% of Breastfed Infants",
  "Oncology: Immunotherapy Combo Boosts Melanoma Survival Rates by 30%",
  "Cardiology: AI-Guided Stent Placement Reduces Heart Attack Risk by 25%",
  "Endocrinology: Thyroid Hormone Analog Improves Lipid Profiles in 80% of Patients",
  "Neurology: Deep Brain Stimulation Cuts Seizure Frequency by 50% in Epilepsy Patients",
  "Psychiatry: Digital CBT App Reduces Anxiety Symptoms by 40% in 8 Weeks",
  "Infectious Diseases: Novel Antibiotic Eradicates MRSA in 90% of Clinical Trial Patients",
  "Oncology: Proton Therapy Reduces Radiation Side Effects by 35% in Pediatric Cancers",
  "Pulmonology: Biologic Tezepelumab Cuts Asthma Exacerbations by 60% in Severe Cases",
  "Cardiology: Omega-3 Supplements Lower Triglycerides by 30% in High-Risk Patients",
  "Endocrinology: Insulin Pump with AI Predicts Hypoglycemia with 85% Accuracy",
  "Neurology: Gene Editing Therapy Shows Promise in Slowing Huntington’s Disease Progression",
  "Oncology: Targeted Therapy Improves Pancreatic Cancer Survival by 20% in Phase 3 Trial",
  "Dermatology: Topical Gene Therapy Reduces Psoriasis Symptoms by 50% in Early Trials",
  "Infectious Diseases: Universal Flu Vaccine Candidate Shows 75% Efficacy Across Strains",
  "Pediatrics: Early Peanut Exposure Reduces Allergy Risk by 80% in High-Risk Infants",
  "Psychiatry: Virtual Reality Therapy Cuts PTSD Symptoms by 45% in Veterans",
  "Cardiology: Bioresorbable Stents Show 95% Success Rate in Coronary Artery Disease",
  "Oncology: AI-Powered Pathology Detects Prostate Cancer with 98% Accuracy",
  "Neurology: Wearable Device Monitors Stroke Recovery with 90% Precision",
  "Endocrinology: Tirzepatide Achieves 15% Weight Loss in Type 2 Diabetes Patients",
  "Infectious Diseases: CRISPR-Based Therapy Eliminates Latent HIV in 60% of Lab Models",
  "Pulmonology: Smart Inhalers Improve Adherence by 40% in Asthma Patients",
  "Oncology: Blood Test Detects Early-Stage Ovarian Cancer with 85% Sensitivity",
  "Cardiology: Remote Monitoring Reduces Heart Failure Readmissions by 30%",
  "Neurology: Tau-Targeted Therapy Slows Cognitive Decline in 50% of Alzheimer’s Patients",
  "Dermatology: Laser Therapy Reduces Acne Scarring by 60% in Clinical Trials",
  "Infectious Diseases: New TB Vaccine Candidate Shows 70% Efficacy in Phase 2 Trials",
  "Oncology: Checkpoint Inhibitors Extend Lung Cancer Survival by 18 Months",
  "Pediatrics: Stem Cell Therapy Restores Vision in 65% of Children with Retinal Disorders",
  "Psychiatry: MDMA-Assisted Therapy Achieves 70% Remission in PTSD Patients",
  "Endocrinology: Closed-Loop Insulin Systems Reduce Hypoglycemia by 50% in Type 1 Diabetes",
  "Cardiology: Gene Therapy Lowers Cholesterol by 40% in Familial Hypercholesterolemia",
  "Oncology: Personalized mRNA Vaccine Shows 60% Response Rate in Melanoma",
  "Neurology: AI-Powered EEG Predicts Seizures 30 Minutes in Advance with 90% Accuracy",
  "Infectious Diseases: Monoclonal Antibodies Cut Ebola Mortality by 35% in Trials",
  "Pulmonology: Anti-Fibrotic Drug Slows IPF Progression by 40% in Phase 3 Study",
  "Dermatology: Microbiome-Based Cream Reduces Rosacea Symptoms by 50%",
  "Oncology: AI-Assisted Radiotherapy Cuts Treatment Time by 25% for Breast Cancer",
  "Cardiology: Plant-Based Diets Lower Heart Disease Risk by 20% in Long-Term Study",
  "Neurology: Exosome Therapy Improves Motor Function in 60% of MS Patients",
  "Infectious Diseases: Nanoparticle Vaccine Shows 80% Efficacy Against RSV in Adults",
  "Pediatrics: Wearable Sensors Detect Autism Symptoms with 85% Accuracy in Toddlers",
  "Psychiatry: Brain-Computer Interface Reduces OCD Symptoms by 40% in Trials",
  "Oncology: PARP Inhibitors Improve Ovarian Cancer Survival by 25% in BRCA-Mutated Cases",
  "Endocrinology: SGLT2 Inhibitors Reduce Kidney Failure Risk by 50% in CKD Patients",
  "Cardiology: 3D-Printed Heart Valves Show 95% Success in Early Trials",
  "Neurology: Blood Pressure Control Cuts Dementia Risk by 30% in Older Adults",
  "Infectious Diseases: Nasal Spray Vaccine Reduces Flu Transmission by 60%",
  "Oncology: Circulating Tumor DNA Test Predicts Cancer Relapse with 90% Accuracy",
  "Dermatology: AI-Diagnostic Tool Identifies Skin Cancer with 95% Sensitivity",
  "Pulmonology: Gene Therapy Restores Lung Function in 50% of Cystic Fibrosis Patients",
  "Psychiatry: Mindfulness App Lowers Depression Symptoms by 35% in 12 Weeks",
  "Pediatrics: Vitamin D Supplementation Cuts Asthma Attacks by 40% in Children",
  "Oncology: Bispecific Antibodies Achieve 65% Response Rate in Multiple Myeloma",
  "Cardiology: Digital Twin Models Predict Heart Attack Risk with 92% Accuracy",
  "Neurology: VR-Based Rehab Improves Stroke Recovery by 30% in 6 Months",
  "Infectious Diseases: New Antifungal Drug Eradicates Candida Auris in 80% of Cases",
  "Endocrinology: GLP-1 Receptor Agonists Cut Obesity-Related Mortality by 20%",
  "Oncology: Robotic Surgery Reduces Complications by 25% in Colorectal Cancer",
  "Dermatology: Peptide-Based Therapy Heals Chronic Wounds in 70% of Patients",
  "Pulmonology: Biologic Mepolizumab Reduces Nasal Polyp Recurrence by 50%",
  "Neurology: Retinal Scans Detect Parkinson’s Disease 7 Years Before Symptoms",
  "Infectious Diseases: mRNA Vaccine for Lyme Disease Shows 85% Efficacy in Trials",
  "Oncology: Tumor-Agnostic Drug Larotrectinib Achieves 75% Response in Rare Cancers",
  "Cardiology: Statin Alternative Bempedoic Acid Lowers CV Events by 15%",
  "Psychiatry: Transcranial Magnetic Stimulation Cuts Bipolar Depression by 50%",
  "Pediatrics: Gene Therapy Cures 90% of Severe Combined Immunodeficiency Cases",
  "Endocrinology: Artificial Pancreas Improves Glycemic Control in 85% of T1D Patients",
  "Oncology: AI-Powered Screening Detects Pancreatic Cancer 2 Years Earlier",
  "Neurology: MicroRNA Therapy Slows ALS Progression by 40% in Early Trials",
  "Infectious Diseases: Broad-Spectrum Antiviral Reduces Viral Load by 70% in Flu Patients",
  "Dermatology: Blue Light Therapy Clears 60% of Severe Acne Cases in 8 Weeks",
];